name: Auto Update Sports

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Sports File
        run: |
          curl -sL "https://thcoban.github.io/ththethao/ttthethao.m3u" -o sports.m3u

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sports.m3u
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update Sports M3U" && git push)
